image: maven:3-jdk-12

build:
  before_script:
    - yum install which -y
    - yum install -y oracle-nodejs-release-el7 oracle-release-el7
    - yum install nodejs -y

  script:
    - mvn clean install sonar:sonar -Dsonar.projectKey=AirbornePanda_vchelper  -Dsonar.organization=airbornepanda -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN