image: maven:3-jdk-12

build:
  before_script:
    - yum install which -y
    - yum install nodejs12 -y

  script:
    - mvn clean install sonar:sonar -Dsonar.projectKey=AirbornePanda_vchelper  -Dsonar.organization=airbornepanda -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_LOGIN